import type { SummaryResult } from "./summarize";

interface ExportData {
  dateRange: string;
  messageCount: number;
  memberCount: number;
  summary: SummaryResult;
  topContributors: { name: string; count: number }[];
}

function esc(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function exportToHtml(data: ExportData): string {
  const topicPills = data.summary.topics
    .map(
      (t) =>
        `<span style="display:inline-block;padding:4px 14px;margin:0 6px 6px 0;font-size:13px;font-weight:600;background:#eef2ff;color:#4338ca;border-radius:9999px;">${esc(t)}</span>`
    )
    .join("");

  const insightItems = data.summary.insights
    .map(
      (ins) =>
        `<li style="margin-bottom:12px;line-height:1.7;color:#374151;"><strong style="color:#111827;">${esc(ins.label)}:</strong> ${esc(ins.text)}</li>`
    )
    .join("");

  const contributorPills = data.topContributors
    .map(
      (c) =>
        `<span style="display:inline-block;padding:4px 14px;margin:0 6px 6px 0;font-size:13px;font-weight:500;background:#f3f4f6;color:#374151;border-radius:9999px;">${esc(c.name)} (${c.count})</span>`
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Chat Summary - ${esc(data.dateRange)}</title>
</head>
<body style="margin:0;padding:0;background:#f9fafb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;">
<div style="max-width:640px;margin:32px auto;background:#ffffff;border-radius:12px;border:1px solid #e5e7eb;overflow:hidden;">

  <!-- Header -->
  <div style="padding:24px 32px;background:#f9fafb;border-bottom:1px solid #f3f4f6;">
    <h1 style="margin:0;font-size:18px;font-weight:700;color:#111827;">${esc(data.dateRange)}</h1>
    <p style="margin:4px 0 0;font-size:13px;color:#6b7280;">${data.messageCount} messages &middot; ${data.memberCount} members</p>
  </div>

  <div style="padding:28px 32px;">

    <!-- Summary -->
    ${data.summary.summary ? `
    <div style="margin-bottom:28px;">
      <h2 style="margin:0 0 8px;font-size:11px;font-weight:700;color:#9ca3af;text-transform:uppercase;letter-spacing:0.05em;">Summary</h2>
      <p style="margin:0;font-size:14px;line-height:1.7;color:#374151;">${esc(data.summary.summary)}</p>
    </div>
    ` : ""}

    <!-- Key Topics -->
    ${data.summary.topics.length > 0 ? `
    <div style="margin-bottom:28px;">
      <h2 style="margin:0 0 10px;font-size:11px;font-weight:700;color:#9ca3af;text-transform:uppercase;letter-spacing:0.05em;">Key Topics</h2>
      <div>${topicPills}</div>
    </div>
    ` : ""}

    <!-- Key Insights -->
    ${data.summary.insights.length > 0 ? `
    <div style="margin-bottom:28px;">
      <h2 style="margin:0 0 10px;font-size:11px;font-weight:700;color:#9ca3af;text-transform:uppercase;letter-spacing:0.05em;">Key Insights</h2>
      <ul style="margin:0;padding-left:20px;font-size:14px;">${insightItems}</ul>
    </div>
    ` : ""}

    <!-- Top Contributors -->
    ${data.topContributors.length > 0 ? `
    <div>
      <h2 style="margin:0 0 10px;font-size:11px;font-weight:700;color:#9ca3af;text-transform:uppercase;letter-spacing:0.05em;">Top Contributors</h2>
      <div>${contributorPills}</div>
    </div>
    ` : ""}

  </div>

  <!-- Footer -->
  <div style="padding:16px 32px;border-top:1px solid #f3f4f6;text-align:center;">
    <p style="margin:0;font-size:11px;color:#9ca3af;">Generated by WhatsApp Chat Summarizer</p>
  </div>

</div>
</body>
</html>`;
}
