import type { SharedData } from "../lib/shareUtils";

interface SharedViewProps {
  data: SharedData;
}

export default function SharedView({ data }: SharedViewProps) {
  const { dateRange, messageCount, memberCount, summary, topContributors } =
    data;

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-2xl mx-auto px-4 py-8 space-y-4">
        {/* Branding */}
        <div className="text-center">
          <h1 className="text-lg font-bold text-gray-900">
            WhatsApp Chat Summary
          </h1>
          <p className="text-xs text-gray-400 mt-1">
            Generated by WhatsApp Chat Summarizer
          </p>
        </div>

        <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
          {/* Header */}
          <div className="px-6 py-4 border-b border-gray-100 bg-gray-50">
            <p className="text-sm font-semibold text-gray-900">{dateRange}</p>
            <p className="text-xs text-gray-500 mt-0.5">
              {messageCount} messages &middot; {memberCount} members
            </p>
          </div>

          <div className="px-6 py-5 space-y-5">
            {/* Summary paragraph */}
            {summary.summary && (
              <div>
                <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-2">
                  Summary
                </h3>
                <p className="text-sm text-gray-700 leading-relaxed">
                  {summary.summary}
                </p>
              </div>
            )}

            {/* Key Topics */}
            {summary.topics.length > 0 && (
              <div>
                <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-2">
                  Key Topics
                </h3>
                <div className="flex flex-wrap gap-2">
                  {summary.topics.map((topic, i) => (
                    <span
                      key={i}
                      className="px-3 py-1 text-xs font-medium bg-indigo-50 text-indigo-700 rounded-full"
                    >
                      {topic}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Key Insights */}
            {summary.insights.length > 0 && (
              <div>
                <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-2">
                  Key Insights
                </h3>
                <ul className="space-y-3">
                  {summary.insights.map((insight, i) => (
                    <li
                      key={i}
                      className="text-sm text-gray-700 leading-relaxed"
                    >
                      <span className="font-semibold text-gray-900">
                        {insight.label}:
                      </span>{" "}
                      {insight.text}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Top Contributors */}
            {topContributors.length > 0 && (
              <div>
                <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-2">
                  Top Contributors
                </h3>
                <div className="flex flex-wrap gap-2">
                  {topContributors.map((c, i) => (
                    <span
                      key={i}
                      className="px-3 py-1 text-xs font-medium bg-gray-100 text-gray-700 rounded-full"
                    >
                      {c.name} ({c.count})
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>

        <p className="text-center text-[11px] text-gray-400">
          This is a shared read-only summary.{" "}
          <a
            href={window.location.origin + window.location.pathname}
            className="text-indigo-500 hover:text-indigo-600"
          >
            Create your own
          </a>
        </p>
      </div>
    </div>
  );
}
